name: SimpleAutoAnnouncer
main: ch.nonameweb.bukkit.plugins.simpleautoannouncer.SimpleAutoAnnouncer
version: 0.7.1
commands:
  announce:
    description: Main Command
  saa:
    description: Main Command Alias