name: SimpleAutoAnnouncer
main: ch.minepvp.bukkit.plugins.simpleautoannouncer.SimpleAutoAnnouncer
version: 1.0.0
commands:
  announce:
    description: Main Command
  saa:
    description: Main Command Alias