name: SimpleAutoAnnouncer
main: ch.minepvp.bukkit.plugins.simpleautoannouncer.SimpleAutoAnnouncer
version: 0.9.2
commands:
  announce:
    description: Main Command
  saa:
    description: Main Command Alias